project1/food/urls.py
from django.urls import path
from . import views

app_name = "food"

urlpatterns = [
    path('',views.index.as_view(),name = 'Index'),
    path('item/',views.item_l,name = "item"),
    path('detail/<int:pk>/',views.detail.as_view(),name = "detail"),
    path('add/',views.add_Item.as_view(),name="add"),
    path('edit/<int:id>/',views.edit_item,name = "edit_item"),
    path('del/<int:id>/',views.item_delete,name = "del"),
    path('profile/',views.profile,name = 'profile')
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_view
from django.contrib.auth import views as authentication_Views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('food.urls')),
    path("register/",user_view.register,name = "register"),
    path("login/",authentication_Views.LoginView.as_view(template_name = 'users/login.html'),name = 'login'),
    path('logout/',authentication_Views.LogoutView.as_view(template_name = 'users/logout.html'),name = 'logout'),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

project1/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_images')
    location = models.CharField(max_length=200)
    
    def __str__(self):
        return self.user.username

project1/food/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from food.models import item
# from django.template import loader
from food.form import addItem
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

# def index(request):
#     items_list = item.objects.all()
#     # template = loader.get_template('food/index.html')
#     context = {
#         'item_list':items_list
#     }
#     return render(request,'food/index.html',context)

#Class based index view

class index(ListView):
    model = item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item_l(request):
    return HttpResponse("the page for item")

# def detail(request,item_id):
#     details = item.objects.get(pk = item_id)
#     context = {
#         'item_detail':details,
#     }
#     return render(request,'food/detail.html',context)

# Class based detail view

class detail(DetailView):
    model = item
    template_name = 'food/detail.html'


# def add_Item(request):
#     form = addItem(request.POST or None)
    
#     if form.is_valid():
#         form.save()
#         return redirect('food:Index')
#     return render(request,'food/add.html',{'form':form})

# Class based Create view

class add_Item(CreateView):
    model = item
    fields = ['item_name','item_desc','item_price','item_img']
    template_name = 'food/add.html'
    
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def edit_item(request,id):
    item_details = item.objects.get(pk = id)
    form = addItem(request.POST or None,instance=item_details)
    
    if form.is_valid():
        form.save()
        return redirect('food:Index')
    return render(request,'food/add.html',{'form':form})

def item_delete(request,id):
    
    item_details = item.objects.get(pk = id)
    if item_delete != None:
        item_details.delete()
        return redirect('food:Index')
    return render(request,'food/detail.html')

@login_required
def profile(request):
    return render(request,'food/profile.html')

project1/user/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .form import userLogin

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = userLogin(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            messages.success(request,f"welcome {username},varify email {email}")
            return redirect('login')
        else:
            print('Error')
    form = userLogin()
    return render(request,"users/register.html",{'form':form})
    

project1/food/templates/food/add.html
{% extends 'food/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">save</button>
    </from>
{%endblock%}

project1/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Head</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href=# class="navbar-brand">FoodApp</a>
    
            <div class="navbar">
                <a class="nav-item nave-link" href="{% url 'food:add' %}">|  Add item  |</a>
                <a class="nav-item nave-link" href="#">|  delete item  |</a>
                <a class="nav-item nave-link" href="#">|  View item  |</a>
                {% if user.is_authenticated %}
                <a class="nav-item nave-link" href="{% url 'logout' %}">|  logout  |</a>
                {% else %}
                <a class="nav-item nave-link" href="{% url 'login' %}">|  login  |</a>
                <a class="nav-item nave-link" href="{% url 'register' %}">|  singUp  |</a>
                {% endif %}
            </div>
        </nav>
        {% if messages %}
            {%for message in  messages%}
            <div class = "alert alert-{{message.tags}}">
                {{message}}
            </div>
            {%endfor%}
        {% endif %}
        {% block body %}
        {% endblock  %}
    </body>
</html>

project1/food/templates/food/detail.html
{% extends 'food/base.html' %}
    {% block body %}
    <ul>
        <li>
            food name : {{object.item_name}}
        </li>
        <li>
            food details : {{object.item_desc}} 
        </li>
        <li>
            food price : {{object.item_price}}
        </li>
        <li>
            uploader name : {{object.user_name}}
        </li>
    </ul>
    <a href="{% url 'food:del' object.pk %}">Delete</a>
    {% endblock %}

project1/food/templates/food/index.html
{% extends 'food/base.html' %}
    {% block body %}
    {% for i in  item_list%}
    <div class ="row">
        <div class = "col-md-3 offset-md-2">
            <img class = "card" height = "150px" src = "{{i.item_img}}">
        </div>
        <div class="col-md-4">
            <h3>{{i.item_name}}</h3>
            <h5>{{i.item_desc}}</h4>
            <h6>${{i.item_price}}</h6>
        </div>

        <div class="col-md-2">
            <a href="{% url 'food:detail' i.pk %}" class="btn btn-success">detail</a>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

    {% comment %} <ul>
        <li>
    <a href = '{% url 'food:detail' i.pk %}'>{{i.pk}}--{{i.item_name}}</a>
        </li>
    </ul> {% endcomment %}

project1/food/templates/food/profile.html
{% load static %}

<h1>{{user.username}}</h1>
{%if user.profile.image %}
<img style='width:150px;height:150px' src = "{{ user.profile.image.url }}" alt="User Image">
{% else %}
<img style='width:150px;height:150px' src = "{% static "img/profilepic.jpg" %}" alt="User Image">
{% endif %}